// Generated by CoffeeScript 1.9.3
(function() {
  describe("StateMachineBox", function() {
    var config, images;
    images = ["<img src='img/closeup.jpg' />", "<img src='img/clouds.jpg' />", "<img src='img/little-tree.jpg' />", "<img src='img/moon.jpg' />", "<img src='img/nature-wlk.jpg' />", "<img src='img/nature1.jpg' />", "<img src='img/sun-flowers.jpg' />", "<img src='img/sun1.jpg' />"];
    config = {
      events: [
        {
          name: "init",
          from: "none",
          to: "initial",
          content: images[0]
        }, {
          name: "left",
          from: "initial",
          to: "left",
          content: images[1]
        }, {
          name: "right",
          from: "initial",
          to: "right",
          content: images[2]
        }, {
          name: "back",
          from: "left",
          to: "initial"
        }, {
          name: "back",
          from: "right",
          to: "initial"
        }, {
          name: "left",
          from: "left",
          to: "left_left",
          content: images[3]
        }, {
          name: "right",
          from: "left",
          to: "left_right",
          content: images[4]
        }, {
          name: "back",
          from: "left_left",
          to: "left"
        }, {
          name: "back",
          from: "left_right",
          to: "left"
        }, {
          name: "left",
          from: "left_left",
          to: "left_left_left",
          content: images[5]
        }, {
          name: "right",
          from: "left_left",
          to: "left_left_right",
          content: images[6]
        }, {
          name: "back",
          from: "left_left_left",
          to: "left_left"
        }, {
          name: "back",
          from: "left_left_right",
          to: "left_left"
        }, {
          name: "left",
          from: "left_left_left",
          to: "final",
          content: images[7]
        }, {
          name: "left",
          from: "left_left_right",
          to: "final"
        }, {
          name: "left",
          from: "left_right",
          to: "final"
        }, {
          name: "right",
          from: "left_left_left",
          to: "final"
        }, {
          name: "right",
          from: "left_left_right",
          to: "final"
        }, {
          name: "right",
          from: "left_right",
          to: "final"
        }
      ],
      callbacks: {
        onbeforeevent: function() {
          return console.log(arguments);
        }
      }
    };
    it("singleton-like behavior", function() {
      return StateMachineBox.MODE = StateMachineBox.MODES.SINGLE;
    });
    return it("multiple-like behavior", function() {
      var popup;
      StateMachineBox.MODE = StateMachineBox.MODES.MANY;
      popup = new StateMachineBox(config, null, {
        buttons: [
          {
            event: "left",
            label: "left",
            locale: false
          }, {
            event: "right",
            label: "right",
            locale: false
          }, {
            event: "back",
            label: "back",
            locale: false
          }
        ],
        width: "700x",
        height: "auto",
        onFailure: function(event) {
          console.warn(event);
          return true;
        }
      });
      popup.draw();
      return expect(true).toBe(true);
    });
  });

}).call(this);
